# Generated by Django 2.2.7 on 2021-02-28 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_title', models.CharField(max_length=300)),
                ('song', models.FileField(upload_to='music')),
                ('song_movie', models.CharField(max_length=300)),
                ('song_singer', models.CharField(max_length=200)),
                ('song_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Category')),
            ],
        ),
    ]
