# Generated by Django 2.2.7 on 2021-02-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(upload_to='song/'),
        ),
    ]
